apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mines-ingress
  namespace: mines
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mines.infodot.co.za
      secretName: mines-tls
  rules:
    - host: mines.infodot.co.za
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: mines-reverb
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mines-app
                port:
                  number: 80
