<?php

namespace Tests\Feature\Api;

use App\Models\Machine;
use App\Models\MineArea;
use App\Models\Team;
use App\Models\User;
use App\Services\OpenApiGenerator;
use App\Services\TeamRoleProvisioner;
use App\Support\PageSize;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

/**
 * Every list endpoint pages the same way.
 *
 * There were four different defaults (15, 20, 25, 50), and seven of the
 * fifteen list endpoints ignored `per_page` entirely while the documentation
 * told everyone that all of them accepted it -- so the parameter you were
 * told to use silently did nothing on nearly half the API, and how many rows
 * you got depended on which endpoint you happened to call.
 */
class PageSizeContractTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Every endpoint that returns a paginated list.
     *
     * @return array<string, array{0: string}>
     */
    public static function listEndpoints(): array
    {
        return [
            'machines' => ['/api/v1/machines'],
            'alerts' => ['/api/v1/alerts'],
            'geofences' => ['/api/v1/geofences'],
            'reports' => ['/api/v1/reports'],
            'notifications' => ['/api/v1/notifications'],
            'notifications unread' => ['/api/v1/notifications/unread'],
            'fuel tanks' => ['/api/v1/fuel/tanks'],
            'fuel transactions' => ['/api/v1/fuel/transactions'],
            'maintenance records' => ['/api/v1/maintenance/records'],
            'maintenance schedules' => ['/api/v1/maintenance/schedules'],
            'machine health' => ['/api/v1/maintenance/health'],
            'assignments available' => ['/api/v1/assignments/available'],
            'webhooks' => ['/api/v1/webhooks'],
        ];
    }

    private function actingUser(): User
    {
        $user = User::factory()->create();
        $team = Team::factory()->create(['user_id' => $user->id]);
        $user->update(['current_team_id' => $team->id]);
        TeamRoleProvisioner::assignRole($user, $team, 'admin');
        Sanctum::actingAs($user->fresh(), ['*']);

        return $user->fresh();
    }

    /**
     * @dataProvider listEndpoints
     */
    public function test_every_list_endpoint_uses_the_same_default_page_size(string $endpoint): void
    {
        $this->actingUser();

        $meta = $this->getJson($endpoint)->assertOk()->json('meta');

        $this->assertSame(
            PageSize::DEFAULT,
            $meta['per_page'],
            "{$endpoint} must default to the same page size as every other list."
        );
    }

    /**
     * @dataProvider listEndpoints
     */
    public function test_every_list_endpoint_honours_per_page(string $endpoint): void
    {
        $this->actingUser();

        $meta = $this->getJson($endpoint.'?per_page=7')->assertOk()->json('meta');

        $this->assertSame(
            7,
            $meta['per_page'],
            "{$endpoint} ignores per_page, which the documentation says every list accepts."
        );
    }

    /**
     * @dataProvider listEndpoints
     */
    public function test_no_list_endpoint_can_be_asked_for_an_unbounded_page(string $endpoint): void
    {
        $this->actingUser();

        // One request must not be able to ask the database for everything.
        $this->getJson($endpoint.'?per_page=100000')
            ->assertStatus(422)
            ->assertJsonValidationErrors('per_page');
    }

    public function test_the_maximum_is_allowed_and_one_more_is_not(string $endpoint = '/api/v1/machines'): void
    {
        $this->actingUser();

        $this->getJson($endpoint.'?per_page='.PageSize::MAX)->assertOk();
        $this->getJson($endpoint.'?per_page='.(PageSize::MAX + 1))->assertStatus(422);
    }

    public function test_paging_actually_pages(): void
    {
        $user = $this->actingUser();
        $area = MineArea::factory()->create(['team_id' => $user->current_team_id]);
        Machine::factory()->count(5)->create([
            'team_id' => $user->current_team_id,
            'mine_area_id' => $area->id,
        ]);

        $first = $this->getJson('/api/v1/machines?per_page=2')->assertOk();
        $this->assertCount(2, $first->json('data'));
        $this->assertSame(5, $first->json('meta.total'));

        $last = $this->getJson('/api/v1/machines?per_page=2&page=3')->assertOk();
        $this->assertCount(1, $last->json('data'));
    }

    public function test_the_documented_rule_matches_the_ceiling_the_code_enforces(): void
    {
        // The rule is written out as a literal at each call site because the
        // docs are generated by reading those literals; this is what stops the
        // duplication drifting from PageSize::MAX.
        $this->assertStringContainsString('max:'.PageSize::MAX, PageSize::RULE_LITERAL);

        $spec = app(OpenApiGenerator::class)->generate();
        $undocumented = [];

        foreach (self::listEndpoints() as [$endpoint]) {
            $path = str_replace('/api/v1', '/api/v1', $endpoint);
            $parameters = collect($spec['paths'][$path]['get']['parameters'] ?? [])->pluck('name');

            if (! $parameters->contains('per_page')) {
                $undocumented[] = $endpoint;
            }
        }

        $this->assertSame([], $undocumented, 'Every list endpoint must document per_page.');
    }
}
