<x-app-layout>
    <div class="space-y-6">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-sm text-[var(--sand)]">Report</p>
                <h1 class="text-3xl font-bold text-[var(--stone)]">{{ $report->title }}</h1>
            </div>
            <a href="{{ route('reports') }}" class="text-sm text-[var(--gold)] hover:text-[var(--gold-soft)]">← Back to Reports</a>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <!-- Summary -->
            <div class="bg-[var(--ink-soft)] rounded-lg border border-[var(--line)] p-6 space-y-4 lg:col-span-2">
                <div class="flex items-center gap-3">
                    <span class="px-3 py-1 rounded-lg text-sm font-semibold {{ $report->status === 'completed' ? 'bg-green-900 text-green-300' : ($report->status === 'pending' ? 'bg-yellow-900 text-yellow-300' : 'bg-white/10 text-[var(--sand)]') }}">
                        {{ ucfirst($report->status) }}
                    </span>
                    <span class="px-3 py-1 rounded-lg text-sm bg-[var(--gold)]/15 text-[var(--gold)] font-semibold">
                        {{ $report->type }}
                    </span>
                    @if($report->format)
                        <span class="px-3 py-1 rounded-lg text-sm bg-white/10 text-[var(--sand)]">Format: {{ strtoupper($report->format) }}</span>
                    @endif
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-[var(--sand)]">
                    <div>
                        <p class="text-[var(--sand)] text-xs">Generated</p>
                        <p class="font-semibold">{{ $report->generated_at?->format('M d, Y H:i') ?? 'Not generated yet' }}</p>
                    </div>
                    <div>
                        <p class="text-[var(--sand)] text-xs">Created</p>
                        <p class="font-semibold">{{ $report->created_at->format('M d, Y H:i') }}</p>
                    </div>
                    <div>
                        <p class="text-[var(--sand)] text-xs">Expires</p>
                        <p class="font-semibold">{{ $report->expires_at?->format('M d, Y H:i') ?? 'No expiry' }}</p>
                    </div>
                    <div>
                        <p class="text-[var(--sand)] text-xs">Generated by</p>
                        <p class="font-semibold">{{ $report->generatedBy?->name ?? 'System' }}</p>
                    </div>
                    @if($report->file_size)
                    <div>
                        <p class="text-[var(--sand)] text-xs">File size</p>
                        <p class="font-semibold">{{ number_format($report->file_size / 1024, 1) }} KB</p>
                    </div>
                    @endif
                </div>

                @if($report->filters)
                    <div class="pt-4 border-t border-[var(--line)]">
                        <h3 class="text-lg font-semibold text-[var(--stone)] mb-2">Filters</h3>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm text-[var(--sand)]">
                            @foreach($report->filters as $key => $value)
                                <div class="flex justify-between bg-white/5 px-3 py-2 rounded border border-[var(--line)]">
                                    <span class="text-[var(--sand)]">{{ Str::title(str_replace('_', ' ', $key)) }}</span>
                                    <span class="font-semibold">{{ is_array($value) ? implode(', ', $value) : $value }}</span>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endif
            </div>

            <!-- Actions -->
            <div class="bg-[var(--ink-soft)] rounded-lg border border-[var(--line)] p-6 space-y-4">
                <h3 class="text-lg font-semibold text-[var(--stone)]">Actions</h3>
                @if($report->file_path && $report->isAvailable())
                    <a href="{{ URL::temporarySignedRoute('reports.signed-download', now()->addMinutes(30), ['report' => $report->id]) }}" class="w-full inline-flex items-center justify-center gap-2 px-4 py-2 bg-[var(--gold)] hover:bg-[var(--gold-soft)] text-[var(--ink)] rounded-lg transition font-display font-semibold">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4"/></svg>
                        Download
                    </a>
                @else
                    <div class="text-sm text-[var(--sand)]">No downloadable file available yet.</div>
                @endif
            </div>
        </div>
    </div>
</x-app-layout>
