<div>
<div class="py-8 animate-fade-in">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Header -->
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
            <div class="animate-slide-in-left">
                <h1 class="text-3xl font-display font-semibold bg-gradient-to-r from-[var(--gold)] to-[var(--umber)] bg-clip-text text-transparent">
                    AI Optimization Dashboard
                </h1>
                <p class="mt-1 text-sm text-[var(--sand)]">
                    Intelligent recommendations and insights powered by AI
                </p>
            </div>
            <div class="flex gap-2 animate-slide-in-right">
                <a href="{{ route('ai-analytics') }}" 
                    class="px-4 py-2 bg-white/10 text-[var(--sand)] rounded-lg hover:bg-white/20 transition font-medium flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>
                    </svg>
                    Analytics
                </a>
                <button wire:click="runAnalysis" wire:loading.attr="disabled" 
                    class="px-4 py-2 bg-[var(--gold)] text-[var(--ink)] rounded-lg hover:bg-[var(--gold-soft)] transition font-medium shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-200">
                    <span wire:loading.remove class="flex items-center gap-2">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
                        </svg>
                        Run AI Analysis
                    </span>
                    <span wire:loading class="flex items-center gap-2">
                        <svg class="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        Analyzing...
                    </span>
                </button>
            </div>
        </div>

        @if (session()->has('success'))
            <div class="mb-4 bg-green-900/20 border-l-4 border-green-500 p-4 rounded animate-slide-down">
                <p class="text-sm text-green-400">{{ session('success') }}</p>
            </div>
        @endif

        @if (session()->has('error'))
            <div class="mb-4 bg-red-900/20 border-l-4 border-red-500 p-4 rounded animate-slide-down">
                <p class="text-sm text-red-400">{{ session('error') }}</p>
            </div>
        @endif

        <!-- Statistics Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            <!-- Total Recommendations -->
            <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-6 transform hover:scale-105 transition-all duration-200 hover:shadow-xl animate-scale-in" style="animation-delay: 0.1s">
                <div class="flex items-center justify-between mb-2">
                    <h3 class="text-sm font-medium text-[var(--sand)]">Total Recommendations</h3>
                    <div class="p-2 bg-[var(--gold)]/15 rounded-lg">
                        <span class="text-2xl">📝</span>
                    </div>
                </div>
                <p class="text-3xl font-bold text-[var(--stone)]">{{ $stats['total_recommendations'] }}</p>
                <p class="text-xs text-[var(--sand)] mt-2">Generated by AI agents</p>
            </div>

            <!-- Pending Actions -->
            <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-6 transform hover:scale-105 transition-all duration-200 hover:shadow-xl animate-scale-in" style="animation-delay: 0.2s">
                <div class="flex items-center justify-between mb-2">
                    <h3 class="text-sm font-medium text-[var(--sand)]">Pending Actions</h3>
                    <div class="p-2 bg-yellow-500/15 rounded-lg">
                        <span class="text-2xl">⏳</span>
                    </div>
                </div>
                <p class="text-3xl font-bold text-yellow-400">{{ $stats['pending_recommendations'] }}</p>
                <p class="text-xs text-[var(--sand)] mt-2">Awaiting implementation</p>
            </div>

            <!-- Implemented -->
            <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-6 transform hover:scale-105 transition-all duration-200 hover:shadow-xl animate-scale-in" style="animation-delay: 0.3s">
                <div class="flex items-center justify-between mb-2">
                    <h3 class="text-sm font-medium text-[var(--sand)]">Implemented</h3>
                    <div class="p-2 bg-green-500/15 rounded-lg">
                        <span class="text-2xl">✅</span>
                    </div>
                </div>
                <p class="text-3xl font-bold text-green-400">{{ $stats['implemented_recommendations'] }}</p>
                <p class="text-xs text-[var(--sand)] mt-2">Successfully applied</p>
            </div>

            <!-- Total Savings -->
            <div class="bg-gradient-to-br from-[var(--gold)] to-[var(--umber)] rounded-lg shadow-lg p-6 text-[var(--ink)] transform hover:scale-105 transition-all duration-200 hover:shadow-xl animate-scale-in" style="animation-delay: 0.4s">
                <div class="flex items-center justify-between mb-2">
                    <h3 class="text-sm font-medium opacity-90">Potential Savings</h3>
                    <div class="p-2 bg-white/20 rounded-lg backdrop-blur-sm">
                        <span class="text-2xl">💰</span>
                    </div>
                </div>
                <p class="text-3xl font-bold">R{{ number_format($stats['potential_savings'], 0) }}</p>
                <p class="text-xs opacity-90 mt-2">Cost optimization potential</p>
            </div>
        </div>

        <!-- Filters -->
        <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-4 mb-6">
            <div class="flex flex-wrap gap-4">
                <div class="flex-1 min-w-[200px]">
                    <label class="block text-sm font-medium text-[var(--sand)] mb-1">Category</label>
                    <select wire:model.live="filters.category" class="w-full rounded-lg border-[var(--line)] bg-white/5 border border-[var(--line)] text-[var(--stone)] transition-all duration-200 focus:ring-2 focus:ring-[var(--gold)]">
                        <option value="">All Categories</option>
                        <option value="fleet">Fleet Optimization</option>
                        <option value="fuel">Fuel Management</option>
                        <option value="maintenance">Maintenance</option>
                        <option value="production">Production</option>
                        <option value="route">Route Planning</option>
                        <option value="cost">Cost Analysis</option>
                    </select>
                </div>

                <div class="flex-1 min-w-[200px]">
                    <label class="block text-sm font-medium text-[var(--sand)] mb-1">Priority</label>
                    <select wire:model.live="filters.priority" class="w-full rounded-lg border-[var(--line)] bg-white/5 border border-[var(--line)] text-[var(--stone)] transition-all duration-200 focus:ring-2 focus:ring-[var(--gold)]">
                        <option value="">All Priorities</option>
                        <option value="critical">Critical</option>
                        <option value="high">High</option>
                        <option value="medium">Medium</option>
                        <option value="low">Low</option>
                    </select>
                </div>

                <div class="flex-1 min-w-[200px]">
                    <label class="block text-sm font-medium text-[var(--sand)] mb-1">Status</label>
                    <select wire:model.live="filters.status" class="w-full rounded-lg border-[var(--line)] bg-white/5 border border-[var(--line)] text-[var(--stone)] transition-all duration-200 focus:ring-2 focus:ring-[var(--gold)]">
                        <option value="">All Statuses</option>
                        <option value="pending">Pending</option>
                        <option value="implementing">Implementing</option>
                        <option value="implemented">Implemented</option>
                        <option value="rejected">Rejected</option>
                    </select>
                </div>
            </div>
        </div>

        <!-- Content Tabs -->
        <div class="mb-6">
            <div class="border-b border-[var(--line)]">
                <nav class="-mb-px flex space-x-8">
                    <button wire:click="$set('activeTab', 'recommendations')" 
                        class="@if($activeTab === 'recommendations') border-[var(--gold)] text-[var(--gold)] @else border-transparent text-[var(--sand)] hover:text-[var(--stone)] hover:border-[var(--line)] @endif whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm transition-all duration-200">
                        Recommendations ({{ $recommendations->count() }})
                    </button>
                    <button wire:click="$set('activeTab', 'insights')" 
                        class="@if($activeTab === 'insights') border-[var(--gold)] text-[var(--gold)] @else border-transparent text-[var(--sand)] hover:text-[var(--stone)] hover:border-[var(--line)] @endif whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm transition-all duration-200">
                        Insights ({{ $insights->count() }})
                    </button>
                    <button wire:click="$set('activeTab', 'alerts')" 
                        class="@if($activeTab === 'alerts') border-[var(--gold)] text-[var(--gold)] @else border-transparent text-[var(--sand)] hover:text-[var(--stone)] hover:border-[var(--line)] @endif whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm transition-all duration-200">
                        Alerts ({{ $predictiveAlerts->count() }})
                    </button>
                </nav>
            </div>
        </div>

        <!-- Recommendations Tab -->
        @if($activeTab === 'recommendations')
            <div class="space-y-4 animate-fade-in">
                @forelse($recommendations as $recommendation)
                    <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-6 border-l-4 
                        @if($recommendation->priority === 'critical') border-red-500 hover:shadow-red-500/10
                        @elseif($recommendation->priority === 'high') border-orange-500 hover:shadow-orange-500/10
                        @elseif($recommendation->priority === 'medium') border-yellow-500 hover:shadow-yellow-500/10
                        @else border-green-500 hover:shadow-green-500/10 @endif
                        transition-all duration-200 hover:shadow-xl transform hover:-translate-y-1">
                        
                        <div class="flex justify-between items-start mb-4">
                            <div class="flex-1">
                                <div class="flex items-center gap-2 mb-2">
                                    <span class="px-3 py-1 text-xs font-medium rounded-full
                                        @if($recommendation->priority === 'critical') bg-red-900 text-red-200
                                        @elseif($recommendation->priority === 'high') bg-orange-900 text-orange-200
                                        @elseif($recommendation->priority === 'medium') bg-yellow-900 text-yellow-200
                                        @else bg-green-900 text-green-200 @endif">
                                        {{ strtoupper($recommendation->priority) }}
                                    </span>
                                    <span class="px-3 py-1 text-xs font-medium rounded-full bg-blue-900 text-blue-200 capitalize">
                                        {{ $recommendation->category }}
                                    </span>
                                    <span class="px-3 py-1 text-xs font-medium rounded-full
                                        @if($recommendation->status === 'implemented') bg-green-900 text-green-200
                                        @elseif($recommendation->status === 'implementing') bg-blue-900 text-blue-200
                                        @elseif($recommendation->status === 'rejected') bg-red-900 text-red-200
                                        @else bg-white/10 text-[var(--sand)] @endif">
                                        {{ ucfirst($recommendation->status) }}
                                    </span>
                                </div>
                                <h3 class="text-lg font-semibold text-[var(--stone)] mb-2">
                                    {{ $recommendation->title }}
                                </h3>
                                <p class="text-sm text-[var(--sand)] mb-3">
                                    {{ $recommendation->description }}
                                </p>
                                <div class="flex items-center gap-4 text-sm">
                                    <div class="flex items-center gap-1">
                                        <svg class="w-4 h-4 text-[var(--sand)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                        </svg>
                                        <span class="text-[var(--sand)]">
                                            {{ round($recommendation->confidence_score * 100) }}% confidence
                                        </span>
                                    </div>
                                    @if($recommendation->estimated_savings > 0)
                                    <div class="flex items-center gap-1">
                                        <svg class="w-4 h-4 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                        </svg>
                                        <span class="text-green-400 font-medium">
                                            R{{ number_format($recommendation->estimated_savings, 0) }} savings
                                        </span>
                                    </div>
                                    @endif
                                    <span class="text-[var(--sand)]">
                                        {{ $recommendation->created_at->diffForHumans() }}
                                    </span>
                                </div>
                            </div>
                            @if($recommendation->status === 'pending')
                            <div class="flex gap-2">
                                <button wire:click="promptRecommendationAction({{ $recommendation->id }}, 'implement')" 
                                    class="px-4 py-2 bg-green-600 text-[var(--stone)] rounded-lg hover:bg-green-700 transition text-sm font-medium transform hover:scale-105">
                                    ✓ Implement
                                </button>
                                <button wire:click="promptRecommendationAction({{ $recommendation->id }}, 'reject')" 
                                    class="px-4 py-2 bg-white/10 text-[var(--sand)] rounded-lg hover:bg-white/20 transition text-sm font-medium">
                                    ✕ Reject
                                </button>
                            </div>
                            @endif
                        </div>
                        
                        @if($recommendation->actionable_steps)
                            <div class="mt-4 pt-4 border-t border-[var(--line)]">
                                <h4 class="text-sm font-semibold text-[var(--sand)] mb-2">Action Steps:</h4>
                                <ul class="list-disc list-inside space-y-1 text-sm text-[var(--sand)]">
                                    @foreach($recommendation->actionable_steps as $step)
                                        <li>{{ $step }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        
                    </div>
                @empty
                    <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-12 text-center">
                        <div class="text-6xl mb-4">🤖</div>
                        <h3 class="text-xl font-semibold text-[var(--stone)] mb-2">No Recommendations Yet</h3>
                        <p class="text-[var(--sand)] mb-4">Run AI Analysis to generate intelligent recommendations</p>
                        <button wire:click="runAnalysis" 
                            class="px-6 py-3 bg-[var(--gold)] text-[var(--ink)] rounded-lg hover:bg-[var(--gold-soft)] transition font-medium shadow-lg hover:shadow-xl transform hover:scale-105">
                            Run Analysis Now
                        </button>
                    </div>
                @endforelse

                @if($showRecommendationConfirm && $pendingRecommendationId)
                    @php $pending = \App\Models\AIRecommendation::find($pendingRecommendationId); @endphp
                    <div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
                        <div class="bg-[var(--ink-soft)] rounded-lg border border-[var(--line)] p-6 w-96 max-h-80 overflow-y-auto">
                            <div class="mb-4">
                                <h3 class="text-lg font-semibold text-[var(--stone)]">Confirm Action</h3>
                                <p class="text-sm text-[var(--sand)] mt-2">You are about to <strong>{{ $pendingRecommendationAction === 'implement' ? 'implement' : 'reject' }}</strong> this recommendation. Proceed?</p>
                            </div>

                            <div class="space-y-3">
                                <div class="text-sm text-[var(--sand)]">
                                    <strong>{{ $pending?->title }}</strong>
                                    <div class="text-[var(--sand)] text-xs mt-1">{{ $pending?->description }}</div>
                                    @if($pending?->proposed_action)
                                        <div class="text-[var(--sand)] text-xs mt-2"><strong>Proposed action:</strong> {{ $pending->proposed_action }}</div>
                                    @endif
                                </div>

                                @if($pendingRecommendationAction === 'reject')
                                    <div>
                                        <label class="block text-xs font-medium text-[var(--sand)] mb-1">Reason for rejecting (required)</label>
                                        <textarea wire:model="rejectReason" rows="2" class="w-full text-sm rounded border-[var(--line)] dark:bg-[var(--ink)] dark:text-[var(--stone)]"></textarea>
                                    </div>
                                @endif
                            </div>

                            <div class="flex gap-2 justify-end mt-6 pt-4 border-t border-[var(--line)]">
                                <button wire:click="cancelRecommendationAction" class="px-4 py-2 bg-white/10 hover:bg-white/20 text-[var(--stone)] rounded">Cancel</button>
                                <button wire:click="confirmRecommendationAction" class="px-4 py-2 bg-[var(--gold)] text-[var(--ink)] rounded hover:bg-[var(--gold-soft)] font-medium">Proceed</button>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        @endif

        <!-- Insights Tab -->
        @if($activeTab === 'insights')
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 animate-fade-in">
                @forelse($insights as $insight)
                    <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-6 hover:shadow-xl transition-all duration-200 transform hover:-translate-y-1">
                        <div class="flex items-start gap-3">
                            <div class="p-2 bg-[var(--gold)]/15 rounded-lg">
                                <span class="text-2xl">💡</span>
                            </div>
                            <div class="flex-1">
                                <h3 class="font-semibold text-[var(--stone)] mb-1">{{ $insight->title }}</h3>
                                <p class="text-sm text-[var(--sand)] mb-2">{{ $insight->insight }}</p>
                                <div class="flex items-center gap-2 text-xs">
                                    <span class="px-2 py-1 bg-white/10 rounded-full text-[var(--sand)] capitalize">
                                        {{ $insight->category }}
                                    </span>
                                    <span class="text-[var(--sand)]">{{ $insight->created_at->diffForHumans() }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @empty
                    <div class="col-span-2 bg-[var(--ink-soft)] rounded-lg shadow-lg p-12 text-center">
                        <div class="text-6xl mb-4">💡</div>
                        <h3 class="text-xl font-semibold text-[var(--stone)] mb-2">No Insights Available</h3>
                        <p class="text-[var(--sand)]">Run AI Analysis to discover insights</p>
                    </div>
                @endforelse
            </div>
        @endif

        <!-- Alerts Tab -->
        @if($activeTab === 'alerts')
            <div class="space-y-4 animate-fade-in">
                @forelse($predictiveAlerts as $alert)
                    <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-6 border-l-4
                        @if($alert->severity === 'critical') border-red-500
                        @elseif($alert->severity === 'high') border-orange-500
                        @else border-yellow-500 @endif
                        hover:shadow-xl transition-all duration-200 transform hover:-translate-y-1">
                        
                        <div class="flex justify-between items-start">
                            <div class="flex-1">
                                <div class="flex items-center gap-2 mb-2">
                                    <span class="px-3 py-1 text-xs font-medium rounded-full
                                        @if($alert->severity === 'critical') bg-red-900 text-red-200
                                        @elseif($alert->severity === 'high') bg-orange-900 text-orange-200
                                        @else bg-yellow-900 text-yellow-200 @endif">
                                        {{ strtoupper($alert->severity) }}
                                    </span>
                                    <span class="px-3 py-1 text-xs font-medium rounded-full bg-blue-900 text-blue-200 capitalize">
                                        {{ str_replace('_', ' ', $alert->alert_type) }}
                                    </span>
                                    @if($alert->is_acknowledged)
                                    <span class="px-3 py-1 text-xs font-medium rounded-full bg-green-900 text-green-200">
                                        ✓ Acknowledged
                                    </span>
                                    @endif
                                </div>
                                <h3 class="text-lg font-semibold text-[var(--stone)] mb-2">{{ $alert->title }}</h3>
                                <p class="text-sm text-[var(--sand)] mb-2">{{ $alert->message }}</p>
                                <div class="flex items-center gap-4 text-sm text-[var(--sand)]">
                                    <span>{{ round($alert->probability * 100) }}% probability</span>
                                    <span>{{ $alert->created_at->diffForHumans() }}</span>
                                </div>
                            </div>
                            @if(!$alert->is_acknowledged)
                            <button wire:click="acknowledgeAlert({{ $alert->id }})" 
                                class="px-4 py-2 bg-[var(--gold)] text-[var(--ink)] rounded-lg hover:bg-[var(--gold-soft)] transition text-sm font-display font-semibold transform hover:scale-105">
                                Acknowledge
                            </button>
                            @endif
                        </div>
                    </div>
                @empty
                    <div class="bg-[var(--ink-soft)] rounded-lg shadow-lg p-12 text-center">
                        <div class="text-6xl mb-4">🚨</div>
                        <h3 class="text-xl font-semibold text-[var(--stone)] mb-2">No Alerts</h3>
                        <p class="text-[var(--sand)]">All systems running smoothly</p>
                    </div>
                @endforelse
            </div>
        @endif
    </div>
</div>

<style>
@keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
}

@keyframes slideInLeft {
    from {
        opacity: 0;
        transform: translateX(-20px);
    }
    to {
        opacity: 1;
        transform: translateX(0);
    }
}

@keyframes slideInRight {
    from {
        opacity: 0;
        transform: translateX(20px);
    }
    to {
        opacity: 1;
        transform: translateX(0);
    }
}

@keyframes slideDown {
    from {
        opacity: 0;
        transform: translateY(-10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

@keyframes scaleIn {
    from {
        opacity: 0;
        transform: scale(0.95);
    }
    to {
        opacity: 1;
        transform: scale(1);
    }
}

.animate-fade-in {
    animation: fadeIn 0.5s ease-out;
}

.animate-slide-in-left {
    animation: slideInLeft 0.5s ease-out;
}

.animate-slide-in-right {
    animation: slideInRight 0.5s ease-out;
}

.animate-slide-down {
    animation: slideDown 0.3s ease-out;
}

.animate-scale-in {
    animation: scaleIn 0.4s ease-out forwards;
    opacity: 0;
}
</style>
</div>
